### ISSUE TITLE
Where to download `tech.lib` and `design.v` files ?

### ISSUE THREAD

**Issue by phuocphn** [scale-lab/DRiLLS#10]
Hi,
Thank you for such great work. Currently, I'm trying to reproduce the result from your paper. But when I run your source code, I have noticed that there is no `tech.lib` and `design.v` file. Could you give me a link to download the sample files ?
I have tried to use the standard cell library and examples from this repository but it doesn't work. https://github.com/The-OpenROAD-Project/asap7  (error: http://i.imgur.com/foeMq5x.png)

Thank you in advance.

**Comment by jknechtel** [comment]
Hi, I'd second this issue. Excellent work and nicely document, but this important detail about library (tech.lib) is missing. ( @phuocphn As for design.v you'd want the EPFL benchmarks from https://github.com/lsils/benchmarks )

@abdelrahmanhosny @sheriefreda Could you please share a copy of the ASAP7 library file used, or describe which library version to obtain from where. The ASAP7 repo hosted with OpenROAD seems the latest official reference, but I think this was put online after the work on DRiLLS was done, so there could be some mismatch.

More specifically, the paper says "typical process corner" but doesn't specify Vth, so I'd guess regular Vth. Then, checking https://github.com/The-OpenROAD-Project/asap7/tree/master/asap7sc7p5t_27/LIB/CCS I'd narrow this down to "*_RVT_TT_ccs_*" but then I'm still confused about merging libraries.

Thanks, best, Johann

**Comment by abdelrahmanhosny** [comment]
Thank you for raising this issue. I will share the library that was used in this work soon. 

Please, give me a couple weeks as I'm currently on vacation and don't have access to the servers. 

Happy holidays!

**Comment by jknechtel** [comment]
Update and as FYI for others: using my best guesses, I've merged the following libraries from https://github.com/The-OpenROAD-Project/asap7/tree/master/asap7sc7p5t_27/LIB/CCS: `asap7sc7p5t_INVBUF_RVT_TT_ccs_201020.lib` and `asap7sc7p5t_SIMPLE_RVT_TT_ccs_201020.lib` into one (as abc cannot load multiple libraries at once, I think). But, that didn't allow me to reproduce the numbers using the scripts provided in `scripts/` so the libraries used for the experiments in the paper must have been different ones.

@abdelrahmanhosny Thanks, just saw your message now. Sure, much appreciated. In case some co-author can provide this earlier, that'd be great! Happy holidays as well!

**Comment by jknechtel** [comment]
@abdelrahmanhosny Belated happy new year to you! I wanted to check if you had some chance to access your servers for the lib?

**Comment by abdelrahmanhosny** [comment]
@jknechtel I hope you have had wonderful holidays. Yes, please email me at `abdelrahman@brown.edu` and I will forward you a download link.
